config/routes.rb
Rails.application.routes.draw do

# Devise
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
  }

  devise_for :owners, controllers: {
    sessions:      'owners/sessions',
    passwords:     'owners/passwords',
    registrations: 'owners/registrations',
    confirmations: 'owners/confirmations'
  }

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

# LINE CALLBACK
  namespace :line do
    post '/callback', to: 'webhook#callback'
  end

# WEB

  # トップページ
  root 'home#index'
  resource :plans, only: [] do
    collection do
      get :free
      get :premium
    end
  end


  # 管理者
  namespace :admins do
    resources :home, only: [:index]
    resources :line_connections, only: [:new, :create]
    resources :line_richmenus
    resources :owners do
      resources :teams, except: [:index], shallow: true do
        patch :update_identifier, on: :member
        resources :shift_submissions, only: [:index]
        namespace :members do
          resources :unapprovals, except: [:new, :create]
        end
        resources :members do
          resources :shift_submissions, except: [:index] do
            resources :shift_adjustments, except: [:index]
          end
        end
      end
    end
    resources :teams, only: [:index]
    resources :users
  end

  # オーナー
  namespace :owners do
    resources :home, only: [:index]
    resource :owner, only: [:edit, :update] do
      get :destroy_unconfirmed_email, on: :collection
      patch :destroy_unconfirmed_email, on: :collection
    end
    resource :deactivation, only: [:show, :destroy]
    resources :teams, except: [:index, :update], shallow: true do
      namespace :members do
        resources :unapprovals, only: [:index, :show, :edit, :destroy]
      end
      patch :update_identifier, on: :member
      resources :payments, only: [:new, :create]
      resources :members, except: [:new, :create, :update] do
        resources :shift_registrations, only: [:show, :new, :edit, :destroy]
      end
      resources :shift_submissions, only: [:show] do
        resources :shift_adjustments, only: [:new, :edit, :destroy]
      end
      resources :shift_tables, only: [:index]
    end
  end

  # ユーザー
  namespace :users do

    # シフト調整者用
    namespace :shift_coordinators do
      resources :teams, only: [:show], shallow: true do
        patch :update_identifier, on: :member
        namespace :members do
          resources :unapprovals, except: [:new, :create, :update]
        end
        resources :members, only: [:index, :show, :edit, :destroy] do
          resources :shift_registrations, only: [:new, :edit, :destroy]
          resources :shift_submissions, only: [:show] do
            resources :shift_adjustments, only: [:new, :edit, :destroy]
          end
        end
        resources :shift_tables, only: [:index]
      end
    end

    # User共通
    resources :home, only: [:index]
    resource :user, only: [:edit, :update] do
      get :destroy_unconfirmed_email, on: :collection
      patch :destroy_unconfirmed_email, on: :collection
    end
    resource :deactivation, only: [:show, :destroy]
    namespace :members do
      resources :unapprovals, only: [:index, :show, :new, :destroy]
      resources :deactivations, only: [:show, :destroy], param: :member_id
    end
    resources :members, only: [:index, :show, :edit], shallow: true do
      resources :shift_submissions, except: [:index, :create, :update]
      resources :shift_registrations, only: [:show]
    end
    resources :line_connections, only: [:new, :create]
  end


  # API

  namespace :api, { format: 'json' } do
    namespace :v1 do

      # 管理者
      namespace :admins do
        resources :users, only: [:index]
        resources :owners, only: [], shallow: true do
          resources :teams, only: [:show, :create, :update] do
            resources :members, only: [:show, :create, :update]
          end
        end
        resources :teams, only: [], shallow: true do
          namespace :members do
            resources :unapprovals, only: [:update]
          end
          resources :members do
            resources :shift_submissions, only: [:new, :edit]
          end
        end
        resources :shift_submissions, only: [:new, :edit], shallow: true do
          resources :shift_adjustments, only: [:show, :new, :edit]
        end
      end

      # オーナー
      namespace :owners do
        resources :teams, only: [:show, :create, :update], shallow: true do
          scope module: :teams do
            resources :calendars, only: [:index]
          end
          resources :shift_tables, only: [:index]
          namespace :members do
            resources :unapprovals, only: [:update]
          end
          resources :members, only: [:show, :update] do
            scope module: :members do
              resources :calendars, only: [:index]
            end
            resources :shift_registrations, only: [:show, :create, :update]
          end
          resources :shift_submissions, only: [:show] do
            resources :shift_adjustments, only: [:show, :create, :update]
          end
        end
      end

      # ユーザー
      namespace :users do

        # ShiftCoordinator
        namespace :shift_coordinators do
          resources :teams, only: [], shallow: true do
            scope module: :teams do
              resources :calendars, only: [:index]
            end
            resources :members, only: [:show, :update] do
              scope module: :members do
                resources :calendars, only: [:index]
                resources :unapprovals, only: [:update]
              end
              resources :shift_submissions, only: [], shallow: true do
                resources :shift_adjustments, only: [:show, :create, :update]
              end
              resources :shift_registrations, only: [:show, :create, :update]
            end
            resources :shift_tables, only: [:index]
          end
        end

        # User共通
        resources :home, only: [:index]
        namespace :members do
          resources :unapprovals, only: [:create]
        end
        resources :teams, only: [:show], shallow: true do
          scope module: :teams do
            resources :calendars, only: [:index]
          end
          resources :members, only: [:show, :update], shallow: true do
            scope module: :members do
              resources :calendars, only: [:index]
            end
            resources :shift_submissions, only: [:show, :create, :update]
          end
        end
      end
    end
  end
end

app/controllers/admins/shift_submissions_controller.rb
class Admins::ShiftSubmissionsController < Admins::ApplicationController
  before_action :set_shift_submission, only: [:show, :edit, :update, :destroy]
  before_action :set_team, only: [:index]
  before_action :set_member, only: [:new, :create]

  def index
    @shift_submissions = @team.shift_submissions.order(submitted_date: :desc).page(params[:page]).per(15)
  end

  def show
    @member = @shift_submission.member
    @shift_adjustment = @shift_submission.shift_adjustment
  end

  def new
    @shift_submission = @member.shift_submissions.build
  end

  def create
    @shift_submission = @member.shift_submissions.build(shift_submission_params)
    if @shift_submission.save
      redirect_to admins_member_url(@member)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @shift_submission.update(shift_submission_params)
      redirect_to admins_shift_submission_url(@shift_submission)
    else
      render :edit
    end
  end

  def destroy
    @shift_submission.destroy
    redirect_to admins_member_url(@shift_submission.member)
  end

  private

  def shift_submission_params
    params.fetch(:shift_submission, {}).permit(
      :submitted_date, :start_time, :end_time
    )
  end

  def update_params
    params.fetch(:shift_submission, {}).permit(
      :status
    )
  end

  def set_shift_submission
    @shift_submission = ShiftSubmission.find(params[:id])
  end

  def set_member
    @member = Member.find(params[:member_id])
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < Admins::ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.order(created_at: :desc).page(params[:page]).per(15)
  end

  def show
    @members = @user.approval_members.order(created_at: :desc).page(params[:page]).per(15)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(create_params)
    if @user.save
      redirect_to admins_users_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(update_params)
      redirect_to admins_user_url(@user)
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admins_users_url
  end

  private

  def create_params
    params.fetch(:user, {}).permit(
      :first_name_kana, :last_name_kana, :first_name, :last_name,
      :email, :password
    )
  end

  def update_params
    params.fetch(:user, {}).permit(
      :first_name_kana, :last_name_kana, :first_name, :last_name, :email
    )
  end

  def set_user
    @user = User.find_by(id: params[:id])
  end
end

app/controllers/api/v1/admins/shift_submissions_controller.rb
class Api::V1::Admins::ShiftSubmissionsController < Api::V1::Admins::ApplicationController
  before_action :set_submission, only: [:edit]
  before_action :set_member, only: [:new]

  def new
    @team = @member.team
  end

  def edit
    @team = @shift_submission.team
  end

  private

  def shift_submission_params
    params.fetch(:shift_submission, {}).permit(
      :submitted_date, :start_time, :end_time
    )
  end

  def set_submission
    @shift_submission = ShiftSubmission.find(params[:id])
  end

  def set_member
    @member = Member.find(params[:member_id])
  end
end

app/controllers/api/v1/admins/users_controller.rb
class Api::V1::Admins::UsersController < Api::V1::Admins::ApplicationController

  def index
    @users = User.all
    render 'index', formats: [:json], handlers: [:jbuilder]
  end
end

app/controllers/api/v1/owners/shift_submissions_controller.rb
class Api::V1::Owners::ShiftSubmissionsController < Api::V1::Owners::ApplicationController
  before_action :set_shift_submission, only: [:show]

  include Api::Owners::AccessControl

  def show
    render json: @shift_submission, only: [:submitted_date, :start_time, :end_time]
  end

  private

  def set_shift_submission
    @shift_submission = ShiftSubmission.find(params[:id])
  end
end

app/controllers/api/v1/users/application_controller.rb
class Api::V1::Users::ApplicationController < ActionController::API
  include ActionController::Flash
  include Banken
  rescue_from Banken::NotAuthorizedError, with: :user_not_authorized
  before_action :authenticate_user!

  private

  def set_team
    @team = Team.find_by(id: params[:id] || params[:team_id])
  end

  def set_member
    @member = Member.find_by(id: params[:id] || params[:member_id])
  end

  def set_current_member
    @current_member = current_user.approval_members.find_by(team_id: @team.id)
  end

  def user_not_authorized
    render json: { message: 'アクセス権限がありません' }, status: 404
  end
end

app/controllers/api/v1/users/home_controller.rb
class Api::V1::Users::HomeController < Api::V1::Users::ApplicationController

  def index
    @members = current_user.approval_members
    render 'index', formats: [:json], handlers: [:jbuilder]
  end
end

app/controllers/api/v1/users/members/calendars_controller.rb
class Api::V1::Users::Members::CalendarsController < Api::V1::Users::ApplicationController
  before_action :set_member

  include Api::Users::AccessControl

  def index
    @shift_submissions = @member.shift_submissions.unapprovals
    @shift_adjustments = @member.shift_adjustments
    @shift_registrations = @member.shift_registrations
    render 'index', formats: [:json], handlers: [:jbuilder]
  end
end

app/controllers/api/v1/users/members/unapprovals_controller.rb
class Api::V1::Users::Members::UnapprovalsController < Api::V1::Users::ApplicationController

  def create
    @join_team_form = JoinTeamForm.new(join_team_form_params)
    if @join_team_form.save(current_user)
      flash[:notice] = '参加を申請しました'
      render json: { status: 200 }
    else
      @error_messages = @join_team_form.errors.full_messages
      render json: { error_messages: @error_messages, status: 400 }
    end
  end

  private

  def join_team_form_params
    params.require(:join_team_form).permit(
      :identifier, :calendar_color
    )
  end
end

app/controllers/api/v1/users/members_controller.rb
class Api::V1::Users::MembersController < Api::V1::Users::ApplicationController
  before_action :set_member, only: [:show, :update]

  include Api::Users::AccessControl

  def show
    render json: @member, only: [:team_id, :calendar_color]
  end

  def update
    if @member.update(member_params)
      flash[:notice] = '登録内容を変更しました'
      render json: { status: 200 }
    else
      @error_messages = @member.errors.full_messages
      render json: { error_messages: @error_messages, status: 400 }
    end
  end

  private

  def member_params
    params.fetch(:member, {}).permit(
      :calendar_color
    )
  end
end

app/controllers/api/v1/users/shift_coordinators/members/calendars_controller.rb
class Api::V1::Users::ShiftCoordinators::Members::CalendarsController < Api::V1::Users::ApplicationController
  before_action :set_member, only: [:index]
  before_action :set_team, only: [:index]

  include Api::Users::ShiftCoordinators::AccessControl

  def index
    @shift_submissions = @member.shift_submissions.unapprovals
    @shift_adjustments = @member.shift_adjustments
    @shift_registrations = @member.shift_registrations
    render 'index', formats: [:json], handlers: [:jbuilder]
  end

  private

  def set_team
    @team = @member.team
  end
end

app/controllers/api/v1/users/shift_coordinators/members/unapprovals_controller.rb
class Api::V1::Users::ShiftCoordinators::Members::UnapprovalsController < Api::V1::Users::ApplicationController
  before_action :set_member, only: [:update]
  before_action :set_team, only: [:update]

  include Api::Users::ShiftCoordinators::AccessControl
  before_action :check_valid_permisson

  def update
    if @member.update(member_params)
      flash[:notice] = 'メンバーの参加を承認しました'
      render json: { status: 200 }
    else
      @error_messages = @member.errors.full_messages
      render json: { error_messages: @error_messages, status: 400 }
    end
  end

  private

  def have_valid_permission?
    @team.manager?(current_user) && !@member.approve
  end

  def member_params
    params.fetch(:member, {}).permit(
      :approve, :role, :shift_coordinator
    )
  end

  def set_team
    @team ||= @member.team
  end
end

app/controllers/api/v1/users/shift_coordinators/members_controller.rb
class Api::V1::Users::ShiftCoordinators::MembersController < Api::V1::Users::ApplicationController
  before_action :set_member, only: [:show, :update]
  before_action :set_team, only: [:show, :update]

  include Api::Users::ShiftCoordinators::AccessControl
  before_action :check_valid_permisson, except: [:update]

  def show
    render json: @member, only: [:team_id, :calendar_color, :role, :shift_coordinator]
  end

  def update
    authorize! @team
    if @member.update(member_params)
      flash[:notice] = 'メンバーの設定内容を変更しました'
      render json: { status: 200 }
    else
      @error_messages = @member.errors.full_messages
      render json: { error_messages: @error_messages, status: 400 }
    end
  end

  private

  def member_params
    params.fetch(:member, {}).permit(
      :role, :shift_coordinator
    )
  end

  def set_member
    @member = Member.find(params[:id])
  end

  def set_team
    @team = @member.team
  end
end

app/controllers/api/v1/users/shift_coordinators/shift_registrations_controller.rb
class Api::V1::Users::ShiftCoordinators::ShiftRegistrationsController < Api::V1::Users::ApplicationController
  before_action :set_shift_registration, only: [:show, :update]
  before_action :set_member, only: [:show, :create, :update]
  before_action :set_team, only: [:show, :create, :update]

  include Api::Users::ShiftCoordinators::AccessControl

  def show
    render json: @shift_registration, only: [:registered_date, :start_time, :end_time]
  end

  def create
    @shift_registration = @member.shift_registrations.build(shift_registration_params)
    @shift_registration.attributes = {
      account_type: current_user.model_name.name,
      account_id: current_user.id
    }
    if @shift_registration.save
      flash[:notice] = 'シフトを登録しました'
      render json: { status: 200 }
    else
      @error_messages = @shift_registration.errors.full_messages
      render json: { error_messages: @error_messages, status: 400 }
    end
  end

  def update
    @shift_registration.attributes = {
      account_type: current_user.model_name.name,
      account_id: current_user.id
    }
    if @shift_registration.update(shift_registration_params)
      flash[:notice] = 'シフトの登録内容を変更しました'
      render json: { status: 200 }
    else
      @error_messages = @shift_registration.errors.full_messages
      render json: { error_messages: @error_messages, status: 400 }
    end
  end

  private

  def shift_registration_params
    params.fetch(:shift_registration, {}).permit(
      :registered_date, :start_time, :end_time
    )
  end

  def set_shift_registration
    @shift_registration = Shift::Registration.find_by(id: params[:id])
  end

  def set_member
    super
    @member ||= @shift_registration&.member
  end

  def set_team
    super
    @team ||= @member&.team
    @team ||= @shift_registration&.team
  end
end

app/views/users/shift_submissions/edit.html.erb
<%= javascript_pack_tag 'users/shift_submissions/edit' %>
<%= stylesheet_pack_tag 'users/shift_submissions/edit' %>


<div class="row">
  <div class="col-md-3">
    <div class="box box-primary">
      <div class="box-body box-profile">
        <h3 class="profile-username text-center"><%= @team.name %></h3>
        <p class="text-muted text-center">営業時間：<%= @team.open_time %>~<%= @team.close_time %></p>
        <ul class="list-group list-group-unbordered">
          <li class="list-group-item">
            <b>希望日</b> <span class="pull-right"><%= @shift_submission.submitted_date %></span>
          </li>
          <li class="list-group-item">
            <b>開始時間</b> <span class="pull-right"><%= @shift_submission.start_time %></span>
          </li>
          <li class="list-group-item">
            <b>終了時間</b> <span class="pull-right"><%= @shift_submission.end_time %></span>
          </li>
        </ul>
        <%= link_to 'キャンセル', users_shift_submission_path(@shift_submission), class: 'btn btn-default btn-block' %>
        <hr>
        <%= link_to '削除', users_shift_submission_path(@shift_submission), method: :delete,
          data: { confirm: '削除してもよろしいですか？' }, class: "btn btn-danger btn-block" %>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <div class="box box-default">
      <div class="box-header with-border">
        <h3 class="box-title">シフト希望変更</h3>
      </div>
      <div class="box-body">
        <div id="shift_submissions_edit"
          data-shift_submission_id="<%= @shift_submission.id %>"
          data-team_id="<%= @team.id %>"></div>
      </div>
    </div>
  </div>
</div>

app/views/users/shift_submissions/index.html.erb
<%= stylesheet_link_tag 'users/fullcalendar' %>
<%= javascript_include_tag 'users/shift_submissions/index' %>

<div class="row">
  <div class="col-md-3">
    <div class="box box-primary">
      <div class="box-body box-profile">
        <h3 class="profile-username text-center"><%= @team.name %></h3>
        <ul class="list-group list-group-unbordered">
          <li class="list-group-item">
            <b>営業開始時間</b> <span class="pull-right"><%= @team.open_time %></span>
          </li>
          <li class="list-group-item">
            <b>営業終了時間</b> <span class="pull-right"><%= @team.close_time %></span>
          </li>
        </ul>
        <%= link_to 'シフトカレンダー', users_member_path(@member), class: 'btn btn-default btn-block' %>
      </div>
    </div>
  </div>
  <div class="col-md-9">
    <div class="box box-primary">
      <div class="box-body no-padding">
        <div id="shift_submissions_calendar" data-member_id="<%= @member.id %>"></div>
      </div>
    </div>
  </div>
</div>

app/views/users/shift_submissions/new.html.erb
<%= javascript_pack_tag 'users/shift_submissions/new' %>
<%= stylesheet_pack_tag 'users/shift_submissions/new' %>

<div class="row">
  <div class="col-md-3">
    <div class="box box-primary">
      <div class="box-body box-profile">
        <h3 class="profile-username text-center"><%= @team.name %></h3>
        <ul class="list-group list-group-unbordered">
          <li class="list-group-item">
            <b>営業開始時間</b> <span class="pull-right"><%= @team.open_time %></span>
          </li>
          <li class="list-group-item">
            <b>営業終了時間</b> <span class="pull-right"><%= @team.close_time %></span>
          </li>
          <li class="list-group-item">
            <b>役職</b> <span class="pull-right"><%= @member.role_i18n %></span>
          </li>
        </ul>
        <%= link_to 'キャンセル', users_member_path(@member), class: 'btn btn-default btn-block' %>
      </div>
    </div>
  </div>
  <div class="col-md-8">
    <div class="box box-default">
      <div class="box-header with-border">
        <h3 class="box-title">シフト希望の提出</h3>
      </div>
      <div class="box-body">
        <div id="shift_submissions_new"
          data-team_id="<%= @team.id %>"
          data-member_id="<%= @member.id %>">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/shift_submissions/show.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="box box-primary">
      <div class="box-body box-profile">
        <h3 class="profile-username text-center"><%= @member.team.name %></h3>
        <ul class="list-group list-group-unbordered">
          <li class="list-group-item">
            <b>提出者</b> <span class="pull-right"><%= @member.user.name %></span>
          </li>
          <li class="list-group-item">
            <b>希望日</b> <span class="pull-right"><%= @shift_submission.submitted_date_format %></span>
          </li>
          <li class="list-group-item">
            <b>希望時間</b> <span class="pull-right"><%= @shift_submission.submitted_time %></span>
          </li>
        </ul>
        <% unless @shift_adjustment %>
          <%= link_to '希望日時変更', edit_users_shift_submission_path(@shift_submission), class: "btn btn-success btn-block" %>
        <% end %>
        <hr>
        <%= link_to 'シフトカレンダー', users_member_path(@member), class: 'btn btn-default btn-block' %>
      </div>
    </div>
  </div>
  <div class="col-md-9">
    <% if @shift_adjustment %>
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">シフト調整済</h3>
          <div class="box-tools">
          </div>
        </div>
        <div class="box-body no-padding">
          <table class="table">
            <tbody>
              <tr>
                <th>調整者</th>
                <th>勤務日</th>
                <th>開始時間</th>
                <th>終了時間</th>
              </tr>
              <tr>
                <td><%= @shift_adjustment.account_name %></td>
                <td><%= @shift_submission.submitted_date_format %></td>
                <td><%= @shift_adjustment.start_time %></td>
                <td><%= @shift_adjustment.end_time %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    <% else %>
      <div class="callout callout-danger">
        <p>シフト希望が承認されていません</p>
      </div>
    <% end %>
  </div>
</div>