config/routes.rb
Rails.application.routes.draw do

# Devise
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
  }

  devise_for :owners, controllers: {
    sessions:      'owners/sessions',
    passwords:     'owners/passwords',
    registrations: 'owners/registrations',
    confirmations: 'owners/confirmations'
  }

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

# LINE CALLBACK
  namespace :line do
    post '/callback', to: 'webhook#callback'
  end

# WEB

  # トップページ
  root 'home#index'
  resource :plans, only: [] do
    collection do
      get :free
      get :premium
    end
  end


  # 管理者
  namespace :admins do
    resources :home, only: [:index]
    resources :line_connections, only: [:new, :create]
    resources :line_richmenus
    resources :owners do
      resources :teams, except: [:index], shallow: true do
        patch :update_identifier, on: :member
        resources :shift_submissions, only: [:index]
        namespace :members do
          resources :unapprovals, except: [:new, :create]
        end
        resources :members do
          resources :shift_submissions, except: [:index] do
            resources :shift_adjustments, except: [:index]
          end
        end
      end
    end
    resources :teams, only: [:index]
    resources :users
  end

  # オーナー
  namespace :owners do
    resources :home, only: [:index]
    resource :owner, only: [:edit, :update] do
      get :destroy_unconfirmed_email, on: :collection
      patch :destroy_unconfirmed_email, on: :collection
    end
    resource :deactivation, only: [:show, :destroy]
    resources :teams, except: [:index, :update], shallow: true do
      namespace :members do
        resources :unapprovals, only: [:index, :show, :edit, :destroy]
      end
      patch :update_identifier, on: :member
      resources :payments, only: [:new, :create]
      resources :members, except: [:new, :create, :update] do
        resources :shift_registrations, only: [:show, :new, :edit, :destroy]
      end
      resources :shift_submissions, only: [:show] do
        resources :shift_adjustments, only: [:new, :edit, :destroy]
      end
      resources :shift_tables, only: [:index]
    end
  end

  # ユーザー
  namespace :users do

    # シフト調整者用
    namespace :shift_coordinators do
      resources :teams, only: [:show], shallow: true do
        patch :update_identifier, on: :member
        namespace :members do
          resources :unapprovals, except: [:new, :create, :update]
        end
        resources :members, only: [:index, :show, :edit, :destroy] do
          resources :shift_registrations, only: [:new, :edit, :destroy]
          resources :shift_submissions, only: [:show] do
            resources :shift_adjustments, only: [:new, :edit, :destroy]
          end
        end
        resources :shift_tables, only: [:index]
      end
    end

    # User共通
    resources :home, only: [:index]
    resource :user, only: [:edit, :update] do
      get :destroy_unconfirmed_email, on: :collection
      patch :destroy_unconfirmed_email, on: :collection
    end
    resource :deactivation, only: [:show, :destroy]
    namespace :members do
      resources :unapprovals, only: [:index, :show, :new, :destroy]
      resources :deactivations, only: [:show, :destroy], param: :member_id
    end
    resources :members, only: [:index, :show, :edit], shallow: true do
      resources :shift_submissions, except: [:index, :create, :update]
      resources :shift_registrations, only: [:show]
    end
    resources :line_connections, only: [:new, :create]
  end


  # API

  namespace :api, { format: 'json' } do
    namespace :v1 do

      # 管理者
      namespace :admins do
        resources :users, only: [:index]
        resources :owners, only: [], shallow: true do
          resources :teams, only: [:show, :create, :update] do
            resources :members, only: [:show, :create, :update]
          end
        end
        resources :teams, only: [], shallow: true do
          namespace :members do
            resources :unapprovals, only: [:update]
          end
          resources :members do
            resources :shift_submissions, only: [:new, :edit]
          end
        end
        resources :shift_submissions, only: [:new, :edit], shallow: true do
          resources :shift_adjustments, only: [:show, :new, :edit]
        end
      end

      # オーナー
      namespace :owners do
        resources :teams, only: [:show, :create, :update], shallow: true do
          scope module: :teams do
            resources :calendars, only: [:index]
          end
          resources :shift_tables, only: [:index]
          namespace :members do
            resources :unapprovals, only: [:update]
          end
          resources :members, only: [:show, :update] do
            scope module: :members do
              resources :calendars, only: [:index]
            end
            resources :shift_registrations, only: [:show, :create, :update]
          end
          resources :shift_submissions, only: [:show] do
            resources :shift_adjustments, only: [:show, :create, :update]
          end
        end
      end

      # ユーザー
      namespace :users do

        # ShiftCoordinator
        namespace :shift_coordinators do
          resources :teams, only: [], shallow: true do
            scope module: :teams do
              resources :calendars, only: [:index]
            end
            resources :members, only: [:show, :update] do
              scope module: :members do
                resources :calendars, only: [:index]
                resources :unapprovals, only: [:update]
              end
              resources :shift_submissions, only: [], shallow: true do
                resources :shift_adjustments, only: [:show, :create, :update]
              end
              resources :shift_registrations, only: [:show, :create, :update]
            end
            resources :shift_tables, only: [:index]
          end
        end

        # User共通
        resources :home, only: [:index]
        namespace :members do
          resources :unapprovals, only: [:create]
        end
        resources :teams, only: [:show], shallow: true do
          scope module: :teams do
            resources :calendars, only: [:index]
          end
          resources :members, only: [:show, :update], shallow: true do
            scope module: :members do
              resources :calendars, only: [:index]
            end
            resources :shift_submissions, only: [:show, :create, :update]
          end
        end
      end
    end
  end
end

app/controllers/admins/members/unapprovals_controller.rb
class Admins::Members::UnapprovalsController < Admins::ApplicationController
  before_action :set_team, only: [:index]
  before_action :set_member, except: [:index]

  def index
    @members = @team.members.unapprovals.order(created_at: :desc).page(params[:page]).per(15)
  end

  def show

  end

  def edit

  end

  def update
    if @member.update(member_params)
      redirect_to admins_team_members_unapprovals_url(@member.team)
    else
      render :edit
    end
  end

  def destroy
    @member.destroy
    redirect_to admins_team_members_unapprovals_url(@member.team)
  end

  private

  def member_params
    params.fetch(:member, {}).permit(
        :role, :approve
    )
  end

  def set_member
    @member = Member.find_by(id: params[:id])
  end
end

app/controllers/admins/members_controller.rb
class Admins::MembersController < Admins::ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  before_action :set_team, only: [:new, :create]

  def index
  end

  def show
    @shift_submissions = @member.shift_submissions.order(submitted_date: :desc).page(params[:page]).per(10)
  end

  def new
    @member = @team.members.build
  end

  def create
    @member = @team.members.build(create_params)
    if @member.save
      redirect_to admins_team_url(@team)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @member.update(update_params)
      redirect_to admins_member_url(@member)
    else
      render :edit
    end
  end

  def destroy
    @member.destroy
    redirect_to admins_team_url(@member.team)
  end

  private

  def create_params
    params.fetch(:member, {}).permit(
      :user_id, :role
    )
  end

  def update_params
    params.fetch(:member, {}).permit(
      :role
    )
  end

  def set_member
    @member = Member.find(params[:id])
  end

  def set_team
    @team = Team.find(params[:team_id])
  end
end

app/controllers/admins/owners_controller.rb
class Admins::OwnersController < Admins::ApplicationController
  before_action :set_owner, only: [:show, :edit, :update]

  def index
    @owners = Owner.order(created_at: :desc).page(params[:page]).per(15)
  end

  def show
    @teams = @owner.teams.order(created_at: :desc).page(params[:page]).per(15)
  end

  def new
    @owner = Owner.new
  end

  def create
    @owner = Owner.new(create_params)
    if @owner.save
      redirect_to admins_owners_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @owner.update(update_params)
      redirect_to admins_owner_url(@owner)
    else
      render :edit
    end
  end

  def destroy
  end

  private

  def create_params
    params.fetch(:owner, {}).permit(
      :first_name_kana, :last_name_kana, :first_name, :last_name,
      :email, :password
    )
  end

  def update_params
    params.fetch(:owner, {}).permit(
      :first_name_kana, :last_name_kana, :first_name, :last_name, :email,
      :max_team_count
    )
  end

  def set_owner
    @owner = Owner.find(params[:id])
  end
end

app/controllers/api/v1/admins/members/unapprovals_controller.rb
class Api::V1::Admins::Members::UnapprovalsController < Api::V1::Admins::ApplicationController
  before_action :set_member, only: [:update]

  def update
    if @member.update(member_params)
      @success_message = 'メンバーの参加を承認しました。'
      render 'api/v1/shared/success', formats: [:json], handlers: [:jbuilder]
    else
      @error_messages = @member.errors.full_messages
      render "api/v1/shared/error_messages", formats: [:json], handlers: [:jbuilder]
    end
  end

  private

  def member_params
    params.fetch(:member, {}).permit(
        :approve, :role, :shift_coordinator
    )
  end

  def set_member
    @member = Member.find_by(id: params[:id])
  end
end

app/controllers/api/v1/admins/members_controller.rb
class Api::V1::Admins::MembersController < Api::V1::Admins::ApplicationController
  before_action :set_member, only: [:show, :update]
  before_action :set_team, only: [:create]

  def show
    render json: @member, only: [:role, :shift_coordinator, :calendar_color]
  end

  def create
    @member = @team.members.build(member_params)
    if @member.save
      @success_message = 'チームを作成しました。'
      render 'api/v1/shared/success', formats: [:json], handlers: [:jbuilder]
    else
      @error_messages = @member.errors.full_messages
      render "api/v1/shared/error_messages", formats: [:json], handlers: [:jbuilder]
    end
  end

  def update
    if @member.update(member_params)
      @success_message = 'チームの登録内容を変更しました。'
      render 'api/v1/shared/success', formats: [:json], handlers: [:jbuilder]
    else
      @error_messages = @member.errors.full_messages
      render "api/v1/shared/error_messages", formats: [:json], handlers: [:jbuilder]
    end
  end

  private

  def member_params
    params.fetch(:member, {}).permit(
      :user_id, :role, :shift_coordinator, :calendar_color, :approve
    )
  end

  def set_member
    @member = Member.find_by(id: params[:id])
  end

  def set_team
    @team = Team.find_by(id: params[:team_id])
  end
end

app/controllers/api/v1/owners/application_controller.rb
class Api::V1::Owners::ApplicationController < ActionController::API
  include ActionController::Flash
  before_action :authenticate_owner!

  private

  def set_team
    @team = Team.find_by(id: params[:team_id])
  end
end

app/controllers/api/v1/owners/members/calendars_controller.rb
class Api::V1::Owners::Members::CalendarsController < Api::V1::Owners::ApplicationController
  before_action :set_member, only: [:index]
  before_action :set_team, only: [:index]

  include Api::Owners::AccessControl

  def index
    @shift_submissions = @member.shift_submissions.unapprovals
    @shift_adjustments = @member.shift_adjustments
    @shift_registrations = @member.shift_registrations
    render 'index', formats: [:json], handlers: [:jbuilder]
  end

  private

  def set_member
    @member = Member.find_by(id: params[:member_id])
  end

  def set_team
    @team = @member.team
  end
end

app/controllers/api/v1/owners/members/unapprovals_controller.rb
class Api::V1::Owners::Members::UnapprovalsController < Api::V1::Owners::ApplicationController
  before_action :set_member, only: [:update]

  include Api::Owners::AccessControl

  def update
    if @member.update(member_params)
      @member.team.increase_stripe_quantity
      flash[:notice] = 'メンバーの参加を承認しました'
      render json: { status: 200 }
    else
      @error_messages = @member.errors.full_messages
      render json: { error_messages: @error_messages, status: 400 }
    end
  end

  private

  def have_valid_permission?
    team = @member.team
    team.owner == current_owner && !@member.approve?
  end

  def member_params
    params.fetch(:member, {}).permit(
        :approve, :role, :shift_coordinator
    )
  end

  def set_member
    @member = Member.find_by(id: params[:id])
  end
end

app/controllers/api/v1/owners/members_controller.rb
class Api::V1::Owners::MembersController < Api::V1::Owners::ApplicationController
  before_action :set_member, only: [:show, :update]

  include Api::Owners::AccessControl

  def show
    render json: @member, only: [:role, :shift_coordinator]
  end

  def update
    if @member.update(member_params)
      flash[:notice] = 'メンバーの登録内容を変更しました'
      render json: { status: 200 }
    else
      @error_messages = @member.errors.full_messages
      render json: { error_messages: @error_messages, status: 400 }
    end
  end

  private

  def member_params
    params.fetch(:member, {}).permit(
      :role, :shift_coordinator
    )
  end

  def set_member
    @member = Member.find(params[:id])
  end
end

app/controllers/api/v1/owners/shift_adjustments_controller.rb
class Api::V1::Owners::ShiftAdjustmentsController < Api::V1::Owners::ApplicationController
  before_action :set_shift_adjustment, only: [:show, :update]
  before_action :set_shift_submission, only: [:create]
  before_action :set_team, only: [:create]

  include Api::Owners::AccessControl

  def show
    render json: @shift_adjustment, only: [:start_time, :end_time]
  end

  def create
    @shift_adjustment = @shift_submission.build_shift_adjustment(shift_adjustment_params)
    @shift_adjustment.attributes = {
      account_type: current_owner.model_name.name,
      account_id: current_owner.id
    }
    if @shift_adjustment.save
      flash[:notice] = 'シフトを調整しました'
      render json: { status: 200 }
    else
      @error_messages = @shift_adjustment.errors.full_messages
      render json: { error_messages: @error_messages, status: 400 }
    end
  end

  def update
    @shift_adjustment.attributes = {
      account_type: current_owner.model_name.name,
      account_id: current_owner.id
    }
    if @shift_adjustment.update(shift_adjustment_params)
      flash[:notice] = 'シフトの調整内容を変更しました'
      render json: { status: 200 }
    else
      @error_messages = @shift_adjustment.errors.full_messages
      render json: { error_messages: @error_messages, status: 400 }
    end
  end

  private

  def shift_adjustment_params
    params.fetch(:shift_adjustment, {}).permit(
      :start_time, :end_time
    )
  end

  def set_team
    super
    @team ||= @shift_submission.team
  end

  def set_shift_adjustment
    @shift_adjustment = Shift::Adjustment.find(params[:id])
  end

  def set_shift_submission
    @shift_submission = ShiftSubmission.find(params[:shift_submission_id])
  end
end

app/controllers/api/v1/owners/shift_registrations_controller.rb
class Api::V1::Owners::ShiftRegistrationsController < Api::V1::Owners::ApplicationController
  before_action :set_shift_registration, only: [:show, :update]
  before_action :set_member, only: [:create]
  before_action :set_team, only: [:create]

  include Api::Owners::AccessControl

  def show
    render json: @shift_registration, only: [:registered_date, :start_time, :end_time]
  end

  def create
    @shift_registration = @member.shift_registrations.build(shift_registration_params)
    @shift_registration.attributes = {
      account_type: current_owner.model_name.name,
      account_id: current_owner.id
    }
    if @shift_registration.save
      flash[:notice] = 'シフトを登録しました'
      render json: { status: 200 }
    else
      @error_messages = @shift_registration.errors.full_messages
      render json: { error_messages: @error_messages, status: 400 }
    end
  end

  def update
    if @shift_registration.update(shift_registration_params)
      flash[:notice] = 'シフトの登録内容を変更しました'
      render json: { status: 200 }
    else
      @error_messages = @shift_registration.errors.full_messages
      render json: { error_messages: @error_messages, status: 400 }
    end
  end

  private

  def shift_registration_params
    params.fetch(:shift_registration, {}).permit(
      :registered_date, :start_time, :end_time
    )
  end

  def set_shift_registration
    @shift_registration = Shift::Registration.find(params[:id])
  end

  def set_member
    @member = Member.find(params[:member_id])
  end

  def set_team
    super
    @team ||= @member.team
  end

end

app/views/owners/members/edit.html.erb
<%= javascript_pack_tag 'owners/members/edit' %>
<%= stylesheet_pack_tag 'owners/members/edit' %>

<div class="row">
  <div class="col-md-3">
    <div class="box box-primary">
      <div class="box-body box-profile">
        <p class="text-muted text-center"><%= @member.user.name_kana %></p>
        <h3 class="profile-username text-center"><%= @member.user.name %></h3>
        <p class="text-muted text-center"><%= @member.user.email %></p>
        <ul class="list-group list-group-unbordered">
          <li class="list-group-item">
            <b>役職</b> <span class="pull-right"><%= @member.role_i18n %></span>
          </li>
          <li class="list-group-item">
            <b>シフト調整権限</b> <span class="pull-right"><%= @member.adjustment_ability %></span>
          </li>
        </ul>
        <%= link_to '戻る', owners_member_path(@member), class: 'btn btn-default btn-block' %>
        <hr>
        <%= link_to '削除', owners_member_path(@member), method: :delete,
          data: { confirm: '削除してもよろしいですか？' }, class: "btn btn-danger btn-block" %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="box box-default">
      <div class="box-header with-border">
        <h3 class="box-title">メンバーの登録内容変更</h3>
      </div>
      <div class="box-body">
        <div id="members_edit" data-member_id="<%= @member.id %>"></div>
      </div>
    </div>
  </div>
</div>

app/views/owners/members/index.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="box box-primary">
      <div class="box-body box-profile">
        <h3 class="profile-username text-center"><%= @team.name %></h3>
        <ul class="list-group list-group-unbordered">
          <li class="list-group-item">
            <b>従業員数</b> <span class="pull-right"><%= @team.members.approvals.count %></span>
          </li>
          <li class="list-group-item">
            <b>営業開始時間</b> <span class="pull-right"><%= @team.open_time %></span>
          </li>
          <li class="list-group-item">
            <b>営業終了時間</b> <span class="pull-right"><%= @team.close_time %></span>
          </li>
          <li class="list-group-item">
            <b>登録可能従業員残数</b> <span class="pull-right"><%= @team.registerable_count %></span>
          </li>
        </ul>
        <input class="btn btn-success btn-block" type="button" value="登録可能従業員数追加" onclick="alert('管理者にお問い合わせください');">
        <hr>
        <%= link_to 'シフトカレンダー', owners_team_path(@team), class: 'btn btn-default btn-block' %>
      </div>
    </div>
  </div>
  <div class="col-md-9">
    <% if @members.any? %>
      <div class="box">
        <div class="box-header">
          <h3 class="box-title">従業員一覧</h3>
          <div class="box-tools">
            <%= paginate @members, theme: 'owners' %>
          </div>
        </div>
        <div class="box-body no-padding">
          <table class="table">
            <tbody>
              <tr>
                <th>名前</th>
                <th>役職</th>
              </tr>
              <% @members.each do |member| %>
                <tr>
                  <td><%= link_to member.user.name, owners_member_path(member) %></td>
                  <td><%= member.role_i18n %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    <% else %>
      <div class="callout callout-danger">
        <p>従業員が登録されていません</p>
      </div>
    <% end %>
  </div>
</div>

app/views/owners/members/show.html.erb
<%= stylesheet_link_tag 'fullcalendar' %>
<%= javascript_include_tag 'owners/members/show' %>

<div class="row">
  <div class="col-md-3">
    <div class="box box-primary">
      <div class="box-body box-profile">
        <p class="text-muted text-center"><%= @member.user.name_kana %></p>
        <h3 class="profile-username text-center"><%= @member.user.name %></h3>
        <p class="text-muted text-center"><%= @member.user.email %></p>
        <ul class="list-group list-group-unbordered">
          <li class="list-group-item">
            <b>チーム名</b> <span class="pull-right"><%= @team.name %></span>
          </li>
          <li class="list-group-item">
            <b>役職</b> <span class="pull-right"><%= @member.role_i18n %></span>
          </li>
          <li class="list-group-item">
            <b>シフト調整権限</b> <span class="pull-right"><%= @member.adjustment_ability %></span>
          </li>
        </ul>
        <%= link_to 'シフト登録', new_owners_member_shift_registration_path(@member), class: "btn btn-primary btn-block" %>
        <hr>
        <%= link_to '設定変更', edit_owners_member_path(@member), class: "btn btn-success btn-block" %>
        <hr>
        <%= link_to '従業員一覧', owners_team_members_path(@member.team), class: 'btn btn-default btn-block' %>
      </div>
    </div>
    <div class="box">
      <div class="box-body no-padding">
        <table class="table">
          <tbody>
            <tr>
              <td>未調整のシフト希望</td>
              <td><span style="color: #3a87ad; opacity: 0.6;"><i class="fa fa-square"></i></span></td>
            </tr>
            <tr>
              <td>調整済みのシフト</td>
              <td><span style="color: #3a87ad;"><i class="fa fa-square"></i></span></td>
            </tr>
            <tr>
              <td>登録されたシフト</td>
              <td><span style="color: #FA3932"><i class="fa fa-square"></i></span></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="col-md-9">
    <div class="box box-primary">
      <div class="box-body no-padding">
        <div id="members_shift_calendar" data-member_id="<%= @member.id %>"></div>
      </div>
    </div>
  </div>
</div>