config/routes.rb
Rails.application.routes.draw do

# Devise
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
  }

  devise_for :owners, controllers: {
    sessions:      'owners/sessions',
    passwords:     'owners/passwords',
    registrations: 'owners/registrations',
    confirmations: 'owners/confirmations'
  }

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations'
  }

# LINE CALLBACK
  namespace :line do
    post '/callback', to: 'webhook#callback'
  end

# WEB

  # トップページ
  root 'home#index'
  resource :plans, only: [] do
    collection do
      get :free
      get :premium
    end
  end


  # 管理者
  namespace :admins do
    resources :home, only: [:index]
    resources :line_connections, only: [:new, :create]
    resources :line_richmenus
    resources :owners do
      resources :teams, except: [:index], shallow: true do
        patch :update_identifier, on: :member
        resources :shift_submissions, only: [:index]
        namespace :members do
          resources :unapprovals, except: [:new, :create]
        end
        resources :members do
          resources :shift_submissions, except: [:index] do
            resources :shift_adjustments, except: [:index]
          end
        end
      end
    end
    resources :teams, only: [:index]
    resources :users
  end

  # オーナー
  namespace :owners do
    resources :home, only: [:index]
    resource :owner, only: [:edit, :update] do
      get :destroy_unconfirmed_email, on: :collection
      patch :destroy_unconfirmed_email, on: :collection
    end
    resource :deactivation, only: [:show, :destroy]
    resources :teams, except: [:index, :update], shallow: true do
      namespace :members do
        resources :unapprovals, only: [:index, :show, :edit, :destroy]
      end
      patch :update_identifier, on: :member
      resources :payments, only: [:new, :create]
      resources :members, except: [:new, :create, :update] do
        resources :shift_registrations, only: [:show, :new, :edit, :destroy]
      end
      resources :shift_submissions, only: [:show] do
        resources :shift_adjustments, only: [:new, :edit, :destroy]
      end
      resources :shift_tables, only: [:index]
    end
  end

  # ユーザー
  namespace :users do

    # シフト調整者用
    namespace :shift_coordinators do
      resources :teams, only: [:show], shallow: true do
        patch :update_identifier, on: :member
        namespace :members do
          resources :unapprovals, except: [:new, :create, :update]
        end
        resources :members, only: [:index, :show, :edit, :destroy] do
          resources :shift_registrations, only: [:new, :edit, :destroy]
          resources :shift_submissions, only: [:show] do
            resources :shift_adjustments, only: [:new, :edit, :destroy]
          end
        end
        resources :shift_tables, only: [:index]
      end
    end

    # User共通
    resources :home, only: [:index]
    resource :user, only: [:edit, :update] do
      get :destroy_unconfirmed_email, on: :collection
      patch :destroy_unconfirmed_email, on: :collection
    end
    resource :deactivation, only: [:show, :destroy]
    namespace :members do
      resources :unapprovals, only: [:index, :show, :new, :destroy]
      resources :deactivations, only: [:show, :destroy], param: :member_id
    end
    resources :members, only: [:index, :show, :edit], shallow: true do
      resources :shift_submissions, except: [:index, :create, :update]
      resources :shift_registrations, only: [:show]
    end
    resources :line_connections, only: [:new, :create]
  end


  # API

  namespace :api, { format: 'json' } do
    namespace :v1 do

      # 管理者
      namespace :admins do
        resources :users, only: [:index]
        resources :owners, only: [], shallow: true do
          resources :teams, only: [:show, :create, :update] do
            resources :members, only: [:show, :create, :update]
          end
        end
        resources :teams, only: [], shallow: true do
          namespace :members do
            resources :unapprovals, only: [:update]
          end
          resources :members do
            resources :shift_submissions, only: [:new, :edit]
          end
        end
        resources :shift_submissions, only: [:new, :edit], shallow: true do
          resources :shift_adjustments, only: [:show, :new, :edit]
        end
      end

      # オーナー
      namespace :owners do
        resources :teams, only: [:show, :create, :update], shallow: true do
          scope module: :teams do
            resources :calendars, only: [:index]
          end
          resources :shift_tables, only: [:index]
          namespace :members do
            resources :unapprovals, only: [:update]
          end
          resources :members, only: [:show, :update] do
            scope module: :members do
              resources :calendars, only: [:index]
            end
            resources :shift_registrations, only: [:show, :create, :update]
          end
          resources :shift_submissions, only: [:show] do
            resources :shift_adjustments, only: [:show, :create, :update]
          end
        end
      end

      # ユーザー
      namespace :users do

        # ShiftCoordinator
        namespace :shift_coordinators do
          resources :teams, only: [], shallow: true do
            scope module: :teams do
              resources :calendars, only: [:index]
            end
            resources :members, only: [:show, :update] do
              scope module: :members do
                resources :calendars, only: [:index]
                resources :unapprovals, only: [:update]
              end
              resources :shift_submissions, only: [], shallow: true do
                resources :shift_adjustments, only: [:show, :create, :update]
              end
              resources :shift_registrations, only: [:show, :create, :update]
            end
            resources :shift_tables, only: [:index]
          end
        end

        # User共通
        resources :home, only: [:index]
        namespace :members do
          resources :unapprovals, only: [:create]
        end
        resources :teams, only: [:show], shallow: true do
          scope module: :teams do
            resources :calendars, only: [:index]
          end
          resources :members, only: [:show, :update], shallow: true do
            scope module: :members do
              resources :calendars, only: [:index]
            end
            resources :shift_submissions, only: [:show, :create, :update]
          end
        end
      end
    end
  end
end

app/controllers/admins/home_controller.rb
class Admins::HomeController < Admins::ApplicationController
  def index
  end
end

app/controllers/api/v1/users/home_controller.rb
class Api::V1::Users::HomeController < Api::V1::Users::ApplicationController

  def index
    @members = current_user.approval_members
    render 'index', formats: [:json], handlers: [:jbuilder]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'home'

  def index

  end
end

app/controllers/owners/home_controller.rb
class Owners::HomeController < Owners::ApplicationController

  def index
    @teams = current_owner.teams.order(created_at: :desc).page(params[:page]).per(15)
  end
end

app/controllers/users/home_controller.rb
class Users::HomeController < Users::ApplicationController
  def index
  end
end

app/views/home/_contact.html.erb
<div id="contact-wrap">
  <div class="container">
    <h3 style="color: #ffffff"><b><%= Settings.title %>運営事務局</b></h3>
    <p>メールアドレス: <a href="mailto:<%= Settings.support_address %>"><%= Settings.support_address %></a></p>
    <br>
    <hr>
    <h2 style="color: #ffffff"><b><%= Settings.title %></b></h2>
  </div>
</div>

app/views/home/_footer.html.erb
<div id="copyrights">
  <div class="container">
    <p>
      &copy; Copyrights <strong><%= Settings.title %></strong>. All Rights Reserved
    </p>
    <div class="credits">
      <!--
        You are NOT allowed to delete the credit link to TemplateMag with free version.
        You can delete the credit link only if you bought the pro version.
        Buy the pro version with working PHP/AJAX contact form: https://templatemag.com/link-bootstrap-agency-template/
        Licensing information: https://templatemag.com/license/
      -->
      Created with Link template by <a href="https://templatemag.com/">TemplateMag</a>
    </div>
  </div>
</div>

app/views/home/_header.html.erb
<div id="headerwrap">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
        <h1><%= Settings.title %></h1>
        <h2>シフト管理を楽にする</h2>
        <div class="spacer"></div>
      </div>
    </div>
  </div>
</div>

app/views/home/_main.html.erb
<div class="container">
  <div class="row mt">
    <div class="col-lg-12">
      <h1></h1>
    </div>
  </div>
  <div class="row mt">
    <div class="col-lg-4">
      <%= image_tag('main01.png', class: 'img-responsive') %>
      <br>
      <h3><b>シフトの調整の手間を削減</b></h3>
      <p>シフトの提出のために店舗に出向く必要はありません。パソコンやスマホからシフトの調整が可能です。</p>
    </div>
    <div class="col-lg-4">
      <%= image_tag('main02.png', class: 'img-responsive') %>
      <br>
      <h3><b>使いやすさを追求したシンプルさ</b></h3>
      <p>シフPONでできることは、シフトの提出とシフトの調整のみ。紙ベースでやるのと同じぐらいのわかりやすさを提供しています。</p>
    </div>
    <div class="col-lg-4">
      <%= image_tag('main03.png', class: 'img-responsive') %>
      <br>
      <h3><b>LINEと連携し、より使いやすく</b></h3>
      <p>シフPONのLINE公式アカウントと、対話的にやり取りするだけでシフトの提出が可能です。</p>
    </div>
  </div>
</div>

app/views/home/_navbar.html.erb
<nav class="menu" id="theMenu">
  <div class="menu-wrap">
    <h1 class="logo"><%= link_to "#{Settings.title}", root_path %></a></h1>
    <i class="fa fa-arrow-right menu-close"></i>

    <% if current_owner %>
      <%= link_to 'ログアウト', destroy_owner_session_path, method: :delete %>
    <% elsif  current_user %>
      <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to '新規登録', new_user_registration_path %>
      <%= link_to 'ログイン', new_user_session_path %>
      <%= link_to 'オーナー様はこちら', new_owner_session_path %>
      <hr>
      <%= link_to '基本プランについて', free_plans_path %>
      <%= link_to 'プレミアムプランについて', premium_plans_path %>
    <% end %>
  </div>

  <div id="menuToggle"><i class="fa fa-bars"></i></div>
</nav>

app/views/home/_plan.html.erb
<div id="services">
  <div class="container">
    <h2><b>料金プラン</b></h2>
    <div class="row mt">
      <div class="col-lg-2 centered">
      </div>
      <div class="col-lg-4">
        <hr>
        <h2><b>基本プラン</b></h2>
        <p style="font-size: 24px; border-bottom: solid 5px #87CEFA"><b>無料</b></p>
        <%= link_to '詳細はこちら', free_plans_path, class: 'btn btn-default btn-large' %>
      </div>
      <div class="col-lg-4">
        <hr>
        <h2><b>プレミアムプラン</b></h2>
        <p><b>１メンバーあたり１０８円（税込）</b></p>
        <%= link_to '詳細はこちら', premium_plans_path, class: 'btn btn-default btn-large' %>
      </div>
    </div>
  </div>
  <br>
</div>

app/views/home/index.html.erb
<%= render 'header' %>
<%= render 'navbar' %>
<%= render 'main' %>
<%= render 'plan' %>
<%= render 'contact' %>
<%= render 'footer' %>